### ISSUE TITLE
对于这种需求“DEBUG包含Bugtags，RELEASE不包含”，有什么建议么

### ISSUE THREAD

**Issue by XUJiahua** [bugtags/Bugtags-Android#7]
我的方案：release下，引用我自己建的bugtags。这样能够保证代码不用改动。

```
    debugCompile 'com.bugtags.library:bugtags-lib:latest.integration'
    releaseCompile project(':mockbugtags')

```              

但是启动release版本，碰到这种问题：
                               
    java.lang.NoSuchMethodError: No static method execute(Lorg/apache/http/client/HttpClient;Lorg/apache/http/client/methods/HttpUriRequest;)Lorg/apache/http/HttpResponse; in class Lcom/bugtags/library/agent/instrumentation/HttpInstrumentation; or its super classes (declaration of 'com.bugtags.library.agent.instrumentation.HttpInstrumentation' appears in /data/app/com.test-1/base.apk)
                                                     at com.iflytek.thridparty.bc.run(Unknown Source)

**Comment by kevinho** [comment]
这是因为插件依然在生效。
你可以选择将 

bugtags {
    appKey "APP_KEY"  //这里是你的 appKey
    appSecret "APP_SECRET"    //这里是你的 appSecret，管理员在设置页可以查看

    trackingNetworkEnabled true //开启网络请求跟踪功能(企业版)
}

这上面的 trackingNetworkEnabled 设置为 false，插件网络跟踪的就不生效，就不会产生上面的错误了

**Comment by XUJiahua** [comment]
谢谢，可行
